### ISSUE TITLE
When Will the Code Be Available?

### ISSUE THREAD

**Issue by yangky11** [stanford-futuredata/Baleen#1]
Hi,

Thanks for doing such great work and planning to release the code. I'm wondering if the code will become available anytime soon.

Best,

**Comment by okhat** [comment]
Hey Kaiyu, Thanks for your interest! I'm actively refactoring [ColBERT](https://github.com/stanford-futuredata/ColBERT) this week and, once that's done, it'll make the Baleen release much easier. Both systems are based on the same backend. Will update here once done.

**Comment by yangky11** [comment]
Thanks!
